[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
lootloop = "CQmvWxzKoxVrVQq798qY1tm699ivLJcvC5XWw8o4DTUj"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"

[hooks]
